### ISSUE TITLE
enbdev.com

### ISSUE THREAD

**Issue by DandelionSprout** [easylist/antiadblockfilters#1]
Large adblock warning on top. I propose `##.main_adbalert`
![image](https://user-images.githubusercontent.com/22780683/121869423-52571700-cd02-11eb-95ea-3be78ff7ce0f.png)

Example page: `http://enbdev.com/download_mod_falloutnv.htm`
Adblockers: uBO 1.35.3rc3 + IDCAC 3.3.0
Browser: Chrome 91.0.4472.101 x64
OS: Windows 10 21H1 x64
Lists in use: 
![image](https://user-images.githubusercontent.com/22780683/121869463-5c791580-cd02-11eb-884c-1b9fe5715ff6.png)

**Comment by dimisa-RUAdList** [comment]
Or: `@@||enbdev.com/_google_ads.js|$script,domain=enbdev.com`

**Comment by smed79** [comment]
https://github.com/easylist/antiadblockfilters/commit/d2c1472b28a807113947b553669a5ba606adb70b
