### ISSUE TITLE
www.wholesomeyum.com

### ISSUE THREAD

**Issue by palzkillm** [easylist/antiadblockfilters#18]
Hello,

on `https://www.wholesomeyum.com/recipes/the-juiciest-burgers-ever/` I see a huge Anti Adblock Warning.

AdGuard on iOS, List Version 2.1.48.67.

screenshot https://github.com/easylist/antiadblockfilters/assets/107746723/b551c141-d154-4e29-b76d-a07bcfcf955f

**Comment by smed79** [comment]
Hello,

fixed in https://github.com/easylist/antiadblockfilters/commit/781d0a1dae49304a991d60a19536845e9293e7e7
