### ISSUE TITLE
кинокрад.net

### ISSUE THREAD

**Issue by CbumDino** [easylist/antiadblockfilters#21]
Hey there, 
It seems the filter `n--80aikhbrhr.net,кинокрад.net##.warning-adblock-box` have both punycode and language specific characters. 

Also i noticed the domain in question is a "park domain" at the moment. 
I believe we can remove it. 

<img width="1512" alt="Screenshot 2024-06-25 at 15 29 07" src="https://github.com/easylist/antiadblockfilters/assets/65717387/b8dca04d-1e99-4659-bcd7-0d7e342a2402">

**Comment by dimisa-RUAdList** [comment]
Ok: https://github.com/easylist/antiadblockfilters/commit/a332d333acd42f8768fe42239c4e9e8bfe5ab90a
