### ISSUE TITLE
thesextube.net

### ISSUE THREAD

**Issue by SpoiledSneeze** [easylist/antiadblockfilters#24]
`thesextube.net##+js(noeval-if, /chp_?ad/)`

**Comment by smed79** [comment]
for ublock° specific filter report [here](https://github.com/uBlockOrigin/uAssets/issues)

**Comment by SpoiledSneeze** [comment]
Not sure if I understand, this site detects adblockers (adguard, brave, etc.) and this custom filter solves the issue.

**Comment by smed79** [comment]
[Adblock Warning Removal List](https://easylist-downloads.adblockplus.org/antiadblockfilters.txt) Does not have any adblock advanced syntax filter.
