### ISSUE TITLE
uploadrar.com

### ISSUE THREAD

**Issue by dportvine** [easylist/antiadblockfilters#7]
`https://uploadrar.com/590qngxc9aw5`

<details>
<summary>Screen</summary>

![2022-11-14_091039](https://user-images.githubusercontent.com/111344219/201596979-290e0547-9a6c-45a0-8e61-4c905799341e.png)
</details>

### List all of your filter lists 

<details>
<summary>Screen</summary>

![2022-08-16_121715](https://user-images.githubusercontent.com/111344219/184844308-054e324a-65ca-4d55-9460-f4210036eac0.png)
</details>

### Tell us about your system configuration 

- Operating system and version: Windows 10 Pro 22H2 x64
- Browser and version: Google Chrome 107.0.5304.107
- Adblock Plus version: Adblock Plus 3.14.2

I understand correctly. There is no point in reporting the detection. For the reason that AWRL is not in ABP?

**Comment by dimisa-RUAdList** [comment]
@smed79
